### ISSUE TITLE
Differences between emd in POT and ExactOptimalTransport

### ISSUE THREAD

**Issue by pnavaro** [JuliaOptimalTransport/ExactOptimalTransport.jl#37]
Hi, perhaps it is a stupid question because I know nothing about OT, I am translating a Python code to Julia. I was wondering why the result from this package is different from the Python version:

```julia
using ExactOptimalTransport
using Distances
import Tulip

# uniform histograms
μ = fill(1/100, 100)
ν = fill(1/200, 200)

# random cost matrix
C = pairwise(SqEuclidean(), rand(1, 100), rand(1, 200); dims=2)

# compute optimal transport map with Tulip
lp = Tulip.Optimizer()

maximum(abs.(emd(μ, ν, C, lp) .- PythonOT.emd(μ, ν, C)))
```
0.002260717489751639

Thanks

**Comment by zsteve** [comment]
Hi @pnavaro ,

In the above you are comparing directly the transport plans, and the nature of the unregularised (Monge-Kantorovich) OT problem is that the solutions are not unique (due to it being a linear program). Since the PythonOT solver uses a network simplex algorithm, whereas ExactOptimalTransport currently employs a generic LP solver, there is no reason to expect the solutions to coincide.
However, you may directly compare the objectives (rather than minimizers), which coincide:
```
julia> ExactOptimalTransport.emd2(μ, ν, C, lp) -  PythonOT.emd2(μ, ν, C)
-4.20636209157838e-8
```
On the other hand, I've got a Julia wrapper of the C++ network simplex solver used in the PythonOT package:
https://github.com/zsteve/EMDNetworkSimplex.jl
But I haven't gotten around to incorporating it to the main package yet. This is on my todo list although I can't guarantee a time by which I will have it done.

**Comment by pnavaro** [comment]
Thank you very much.
